services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root@password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - ./mariadb:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "8080:80"
    networks:
      - internal
    # volumes:
    #   - ./web:/var/www/html
  
networks:
  internal:
    driver: bridge